name: CI to Docker Hub

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# help from https://pet2cattle.com/2021/09/build-multiarch-container-github-action
# for solving the qemu problem (the "pip install" error)
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo 
        uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.9

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract sanitised branch name
        shell: bash
        # run: source scripts/env.sh && echo "##[set-output name=sanitised_branch;]$(get_sanitised_branch_name)"
        run: |
          echo "::set-output name=sanitised_branch_name::$(source scripts/env.sh && get_sanitised_branch_name)"
        id: extract_branch

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm/v6,amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wake-on-lan-mqtt-proxy:${{steps.extract_branch.outputs.sanitised_branch_name}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
